### ISSUE TITLE
pypi.org Package cant do MTC Tentant JWT auth

### ISSUE THREAD

**Issue by mwatermolen** [cylance/python-cyapi#15]
The https://pypi.org/project/cyapi/ Package is very old and lacks support for auth to Tenants via MTC

**Comment by joedelsol** [comment]
The library on GitHub actually does what you are claiming it does not. You are correct that the updates have not been pushed to pypi. There are a few other additions that will go in before the next push to pypi. Can expect the sync by March 2021
