### ISSUE TITLE
AttributeError: 'CyAPI' object has no attribute 'access_token_expiration' 

### ISSUE THREAD

**Issue by mwatermolen** [cylance/python-cyapi#16]
Hello, I am receiving an AttributeError when tring to use the module in Tenant mode. It seems like the CyAPI.s is not being set not even to `None`

Here is the code I am using

```python
 CyAPI(mtc=False, tid=self.ID, app_id=self.MTC.appId, app_secret=self.MTC.appSecret, tenant_app=True, tenant_jwt=self.jwt)
```

Whole section
```python
class Tenant_API():
    def __init__(self, MTCc, ID, NAME):
        self.MTC = MTCc
        self.ID = ID
        self.NAME = NAME
        self.MTC_API =  MTC_API(
            MTCc.name,
            MTCc.appId,
            MTCc.appSecret
        )
        self.jwt = self.MTC_API.getTenantAuthToken(ID)
        self.API = CyAPI(mtc=False, tid=self.ID, app_id=self.MTC.appId, app_secret=self.MTC.appSecret, tenant_app=True, tenant_jwt=self.jwt)   # Building python-cyapi via SRC 

    def CylancePolicySync(self):
        Policies = self.API.get_policies().data      
        for policy in Policies:
            processPolicybyID(self, policy['id'])
```

Here is the output.
```
[2021-02-19 14:55:17,323: ERROR/ForkPoolWorker-4] Task cylance.tasks.CylancePolicySync[2c937f91-6ae4-4a53-af16-de99f8b7f558] raised unexpected: AttributeError("'CyAPI' object has no attribute 'access_token_expiration'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/code/cylance/tasks.py", line 103, in CylancePolicySync
    APIt.CylancePolicySync()                            # RUN API JOB
  File "/code/cylance/cylance.py", line 169, in CylancePolicySync
    Policies = self.API.get_policies().data
  File "/usr/local/lib/python3.9/site-packages/cyapi/mixins/_Policies.py", line 26, in get_policies
    policies = self.get_list_items("policies", **kwargs)
  File "/usr/local/lib/python3.9/site-packages/cyapi/cyapi.py", line 452, in get_list_items
    urls = self._generate_urls(type_name, detail=detail, page_size=limit, params=params, total_pages=total_pages)
  File "/usr/local/lib/python3.9/site-packages/cyapi/cyapi.py", line 387, in _generate_urls
    response = self._make_request("get",baseURL)
  File "/usr/local/lib/python3.9/site-packages/cyapi/cyapi.py", line 260, in _make_request
    if datetime.utcnow() > self.access_token_expiration or self.req_cnt >= 9500:
AttributeError: 'CyAPI' object has no attribute 'access_token_expiration'
```

**Comment by joedelsol** [comment]
I may be missing something you are doing, but based on the info I see, I believe you are not setting up the API object correctly. As a result, you don't have a session setup with the token.

Can you compare the way you setup the object with the examples? 
https://github.com/cylance/python-cyapi/blob/master/examples/simple_setup.py

**Comment by mwatermolen** [comment]
@joedelsol You were right, I was receiving an HTTP/403 on the MTC EP for the Tenant JWT.
![image](https://user-images.githubusercontent.com/73605619/108598227-0b5ba500-7352-11eb-90bf-758aa957c3ba.png)



However I managed to resolve the issue on JWT generation, I tested this URL in postman w/ the JWT that this program made just fine .

---
### Tenant JWT and python Requests:
![image](https://user-images.githubusercontent.com/73605619/108598250-2dedbe00-7352-11eb-9153-c9e657218f8c.png)

---
### Tenant [Get Polices](https://protectapi.cylance.com/policies/v2/?page=1&page_size=200) using JWT & Postman is SUCCESSFULL
![image](https://user-images.githubusercontent.com/73605619/108598281-54135e00-7352-11eb-89f8-89646d1dfc07.png)

---
### However Using the JWT, and CyAPI it seems the HTTP response is falling an assetion for < 300 
```python
self.API = CyAPI(mtc=False, tid=self.ID, app_id=self.MTC.appId, app_secret=self.MTC.appSecret, tenant_app=True, tenant_jwt=self.jwt)   # COMPILING python-cyapi via SRC DUE TO ME :( .src/
```
```
2021-02-20 07:41:34,697: ERROR/ForkPoolWorker-4] Task cylance.tasks.CylancePolicySync[044b99bb-44bc-4376-bfdd-a0e7def6e689] raised unexpected: AssertionError()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 197, in _inner
    reraise(*exc_info)
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 54, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/celery.py", line 192, in _inner
    return f(*args, **kwargs)
  File "/code/cylance/tasks.py", line 105, in CylancePolicySync
    APIt.CylancePolicySync()                            # RUN API JOB
  File "/code/cylance/cylance.py", line 178, in CylancePolicySync
    Policies = self.API.get_policies().data
  File "/code/cylance/src/cyapi/mixins/_Policies.py", line 26, in get_policies
    policies = self.get_list_items("policies", **kwargs)
  File "/code/cylance/src/cyapi/cyapi.py", line 452, in get_list_items
    urls = self._generate_urls(type_name, detail=detail, page_size=limit, params=params, total_pages=total_pages)
  File "/code/cylance/src/cyapi/cyapi.py", line 388, in _generate_urls
    assert response.is_success
AssertionError
```


![image](https://user-images.githubusercontent.com/73605619/108597647-aef78600-734f-11eb-8b62-785f1aac5803.png)

---
## On a side note, Is this tool ***seriously supported***? 

This git seems in a state of disrepair, Please dont get me wrong I appearance the push towards opensource. But if this is not going to be seriously maintained **ANY NEWCOMERS NEED TO BEAWARE**   it frankly may be simpler to start from scratch.

 Does this repo have any plans for:
-  **Better Error Handling**
- **Dev Branches** or at a minimum **Releases**
-  Not to mention *any* documentation on this ***tenant JTW Auth***
- **Some semblance of a release cycle** - 2/20/21 Today 
![image](https://user-images.githubusercontent.com/73605619/108597892-ea468480-7350-11eb-8217-fed9afc768b4.png)

**Comment by joedelsol** [comment]
I apologize that I missed that you were attempting to leverage the functions from the MTC.. I should have referenced the two examples that are MTC specific. I hope you found those in the examples folder. 

I appreciate your other comments and enjoy that we are on the same page. 

The code on GitHub is substantially improved from our first release to pypi at the end of 2019. This is a project that was given birth out of our Sales Engineering. Very little time was available for this project until the end of 2020, when the MTC Auth and Endpoints were added. We did our best to validate and implement pull requests and to those people who contributed, we want to share our appreciation!

Aligned with your comment, I also feel that at least a little better Error Handling would be appreciated by users, rather than just assertions that dump you out. Some of this work is in the GitHub code, but I have a note to improve the exact assertion you were failing on, before pushing to pypi again. 

Following that, the need for additional documentation has been recognized and on the TODO list. The primary focus will be authentication and where to find the official documentation for the endpoints.

In addition, there is the pyJWT newer version support that could use some effort.

This library is still currently supported as a best effort and open source. Stay tuned for options that have official corporate support.

**Comment by joedelsol** [comment]
In support of your dev efforts with the library, I appreciate your custom code, but as quick validation of the library and the functionality it provides I'd like to make a troubleshooting suggestion.

Can you leverage the example provided in [https://github.com/cylance/python-cyapi/blob/master/examples/MTC_tenants_loop.py](https://github.com/cylance/python-cyapi/blob/master/examples/MTC_tenants_loop.py)

and replace line 117
resp = APITenant.get_devices_extended()

with 
resp = APITenant.get_policies()
pprint(resp.data)
exit()  ## Just to ignore the rest of the example code

Assuming this will print the policies from the first of the tenants, you should be able to continue toward your objective.

**Comment by joedelsol** [comment]
Have you found success with your auth issues? If not, I recommend you update to the lates release of the library and see if the enhanced error handling helps.

Appreciate your feedback!

**Comment by mwatermolen** [comment]
@joedelsol I did manage to get it working! Thank you for the hard work to get this library back upto speed it doesn't go unappreciated 🥇 .

After some troubleshooting and importing directly, one of the main issues was that the `API.create_conn()` wasn't called, leading to a mess to troubleshoot in Kubernetes. Is there any reason this cant be called for the user on init?

 For example adding `self.create_conn()` to [cyapi.py#L113](https://github.com/cylance/python-cyapi/blob/f174d4a8d124006cf2c180725fe569f70566a3ae/cyapi/cyapi.py#L113) 
```python  
 def __init__(self, tid=None, app_id=None, app_secret=None, region="NA", mtc=False, tenant_app=False, tenant_jwt=None):
        self.tid_val = tid
        self.app_id = app_id
        self.app_secret = app_secret
        self.jwt = None
        self.region = region
        self.mtc = mtc
        self.tenant_app = tenant_app
        self.tenant_jwt = tenant_jwt

        if self.mtc:
            self.baseURL = "https://api-admin.cylance.com/public/{}/".format(self.regions[region]['mtc_url'])
        else:
            self.baseURL = "https://protectapi{}.cylance.com/".format(self.regions[region]['url'])
        self.debug_level = debug_level
        self.s = None
        self.req_cnt = 0
        self.create_conn()
```

**Comment by joedelsol** [comment]
That is an interesting idea, but seems at first glance that would be a breaking change. Beyond that, I'm assuming there is a likely a reason we didn't do that. It is worth reviewing.

Since you have troubleshoot and resolved the issue that was cause for opening, I'll close this out. Feel free to open other issues or contribute.
