### ISSUE TITLE
Invalid URL error when trying to delete devices.

### ISSUE THREAD

**Issue by jowj** [cylance/python-cyapi#2]
Hello,

I receive an "invalid url" error when I try and delete devices using this code ( these are just fake IDs, I used real ones when testing ):

```python
API.create_conn()
API.delete_devices(['id1', 'id2'])
```

It seems like `delete_devices` calls up to `_make_request`. Within the context of `_make_request` I get this info (notice that delete fails, but get, with the same URL, functions fine):

```python
-> if data:
(Pdb) ApiResponse(self.s.delete(url, json=data)).is_success
False
(Pdb) ApiResponse(self.s.get(url, json=data)).is_success
True
(Pdb) data
{'device_ids': ['id', 'id2'], 'callback_url': ''}
(Pdb) url
'https://protectapi.cylance.com/devices/v2'
(Pdb) ApiResponse(self.s.delete(url, json=data)).errors
{'message': 'The url provided is not valid.'}
```

CyAPI info:
name         : cyapi
version      : 0.9.17
description  : Python bindings for Cylance Console

Do I need to be manually setting a different URL for the `delete_devices` method somewhere? Or am I not giving it the right permissions somewhere maybe? Any direction you could give me would be appreciated :)

**Comment by joshlemos** [comment]
Fixed in [89fd137](https://github.com/cylance/python-cyapi/commit/43f382033a7a4749d9af694ee31d060b79ce2544). It is more Pythonic to use None for a default rather than an empty string.
