### ISSUE TITLE
Updating a device

### ISSUE THREAD

**Issue by mahdialibi** [cylance/python-cyapi#23]
Hi,
I was trying to update zones for a device , so i created this method

> def device_add_remove_zone(id,add_zone_ids=[],remove_zone_ids=[]):
    x={}
    the_device=API.get_device(id).data #getting the device data
    x["name"]=the_device.get("name")
    x["policy_id"]=the_device.get("policy")["id"] #getting the policy and assigning it to the device
    x["add_zone_ids"]=add_zone_ids
    x["remove_zone_ids"]=remove_zone_ids
    print(json.dumps(x))
    t=API.update_device(id,json.dumps(x))
    return t
and after that i call it 

> a=device_add_remove_zone(device1.get("id"),[zone_maf.get("id")],[zone_default.get("id")])

it displays the json like this

> {"name": "WWD-STD-X21", "policy_id": "fbbda5646-abf6-4f8d-b6d5-4485c8bbe4ac", "add_zone_ids": ["52ae2b22-f960-40e3-8e97-8cfdf7ae0381"], "remove_zone_ids": ["9441g59f-2830-41e3-b05d-44d979adf50a"]}

but it does not update the device
i have status code =400
the errors code is:  {'message': 'There is no data to update the device resouce with.'}

I dont know if its an error from me or a bug
thank you

**Comment by joedelsol** [comment]
I’m assuming you determined the issue was not caused by the library?

Just checking, since there are no closing comments.

Thanks!

~~
Joe Delsol
