### ISSUE TITLE
API.get_threat error

### ISSUE THREAD

**Issue by nsmfoo** [cylance/python-cyapi#26]
Hi,

I'm a bit curious regarding the different handling of these two methods when it comes to an empty result (searching for a hash that is not present in the tenant)

Works: API.get_threat_devices(sha256)  returns a 200 OK and an empty array as one could expect

Fails: API.get_threat(sha256), "dies" with the following error message

scanner.py", line 37, in _scan_once
    nextchar = string[idx]
IndexError: string index out of range

The expected outcome is the same as with the first request (200 OK and an empty array)

I'm not ruling out misstakes on my end, but that should be easy to verify out by supplying both a checksum that exist in the tenant and one that does not for both methodes.

Let me know if you need more information or like me to test something.

**Comment by joedelsol** [comment]
Sorry for the delay.. We have not been able to replicate the use as you describe. We will assume you discovered an error related to consuming the dict that is returned in 'response.data'. 

If you still believe this is an issue, it would help to have enough of the code block to understand what is happening around line 37 of scanner.py.
