### ISSUE TITLE
Update Device Policy Example

### ISSUE THREAD

**Issue by camaro23** [cylance/python-cyapi#27]
Hey Guys,

I am looking to have a script that will take a device and update the policy on it. Does anyone have one that they would not mind sharing with me?

Thanks in advance!

**Comment by joedelsol** [comment]
Are you thinking to switch the policy to another existing policy or change something specific about the one that is currently being used by the device?

--
Joe Delsol

**Comment by camaro23** [comment]
Hey @joedelsol - thanks for getting back to me. I am looking to switch the policy to another existing policy. I am thinking a flow of logic would be to provide a list of device ids that loops and changes the policy id to the new one I provide. I am thinking the update_device def is what I need to call:  

def update_device(self, device_id, device):
        """endpoint: /devices/v2/{unique_device_id}"""
        baseURL = self.baseURL + "devices/v2/{}".format(device_id)
        return self._make_request("put",baseURL, data=device)

And then add policy_id like in the below screenshot:

![image](https://user-images.githubusercontent.com/32074358/113807048-09467d80-9729-11eb-9d99-3d64d2eff38c.png)


I am not sure how unique my use case may be, but I was wondering if anyone or yourself have already created an example that does this very task?

Thanks again for the help!

**Comment by joedelsol** [comment]
Yes, that likely is the way to accomplish changing the policy of a list of devices.

I didn’t double check the details, but that sounds like how I would probably do it.

--
Joe Delsol - 916-802-7606

**Comment by joedelsol** [comment]
Let me know is you need to revisit this, but seems like you are happily moving forward!
