### ISSUE TITLE
pyjwt latest version has breaking change

### ISSUE THREAD

**Issue by jthack** [cylance/python-cyapi#3]
I had latest pyjwt before attempting to use cyapi. I kept getting the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\code\python36\lib\site-packages\cyapi\cyapi.py", line 104, in create_conn
    self.jwt = self._get_jwt()
  File "C:\code\python36\lib\site-packages\cyapi\cyapi.py", line 154, in _get_jwt
AttributeError: module 'jwt' has no attribute 'encode'
```

So I googled and found this: https://github.com/flavors/django-graphql-jwt/issues/161

I checked my version of pyjwt and I was on 1.7.x so it should have worked, but it didn't. After fighting with it a bunch, I just downgraded to the version of pyjwt mentioned in your files:
`pip3 install pyjwt==1.5.3`

And it started working. Not sure if you want to file an issue with pyjwt or change your library to work with latest. Thanks.

**Comment by joedelsol** [comment]
Thank you for documenting this. It helped many users!

It is possible that 1.7.x was not the issue, after all, but rather a secondary jwt library discovered while troubleshooting similar issues for others. 

After version testing each PyJWT release from 1.5.3 to 2.0.1, it appears that version 2.0.0 introduced the breaking changed where the output type changed from byte to string. The resulting error 
`encoded = jwt.encode(claims, self.app_secret, algorithm='HS256').decode('utf-8')
AttributeError: 'str' object has no attribute 'decode'`

has been resolved to allow for backward and forward compatibility in release 1.0.20.
