### ISSUE TITLE
Unable to use get_zone_devices if zone value is null

### ISSUE THREAD

**Issue by jowj** [cylance/python-cyapi#7]
Hey there,

Reporting an issue and looking for a work around.

`get_zone_devices()` uses the zone unique ID as part of the URL. This works for most use cases, but if you want to report on devices without a zone there doesn't seem to be a way to use this.

I've also looked at pulling just all device data and grouping them by null/none/"" value in a zone field, except that devices don't have a zone field.

Is there another way to report on devices missing zones?

**Comment by sh1dow3r** [comment]
Facing the same issue, is there a workaround for this kind of request.. [API Documentation](https://docs.blackberry.com/content/dam/docs-blackberry-com/release-pdfs/en/cylance-products/api-and-developer-guides/Cylance%20User%20API%20Guide%20v2.0%20rev24.pdf) dose not seem to support/mention it.

**Comment by joedelsol** [comment]
You would test the result of get_device_zones (a list).. Here is a sample snippet.

```
API.create_conn()

devices = API.get_devices()
for d in devices.data:
    zones = API.get_device_zones(d.get("id"))
    if not zones.data:
        print(f"DEVICE: {d.get('name')}")
        print("No Zone Attached")
```
